### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'src/session.json'

### ISSUE THREAD

**Issue by lCyPh3r** [EchterAlsFake/Osintgram2#1]
Error after login:

Traceback (most recent call last):
  File "C:\Users\bobme\Desktop\Tools\Osintgram2\Osintgram.py", line 509, in <module>
    Osintgram_like_datalux()
  File "C:\Users\bobme\Desktop\Tools\Osintgram2\Osintgram.py", line 82, in __init__
    self.login()
  File "C:\Users\bobme\Desktop\Tools\Osintgram2\Osintgram.py", line 175, in login
    with open("src/session.json", "w") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'src/session.json'

**Comment by EchterAlsFake** [comment]
Fixed with commit  ```51808d7```

It was just a simple logical flaw. Thank you for reporting, have a nice day :)

**Comment by lCyPh3r** [comment]
tysm
