### ISSUE TITLE
error after executing codes

### ISSUE THREAD

**Issue by parsa-ui** [EchterAlsFake/Osintgram2#4]
this error showed after i execute commands on debian vps:

T) Set Target
0) - Login             Needed for private account's you are following to
1) - addrs             Get all registered addressed by target photos
2) - captions          Get user's photos captions
3) - comments          Get total comments of target's posts
4) - followers         Get target followers
5) - followings        Get users followed by target
6) - fwersemail        Get email of target followers
7) - fwingsemail       Get email of users followed by target
8) - fwersnumber       Get phone number of target followers
9) - fwingsnumber      Get phone number of users followed by target
10) - info             Get target info
11) - likes            Get total likes of target's posts
12) - mediatype        Get user's posts type (photo or video)
13) - photos           Download user's photos in output folder
14) - propic           Download user's profile picture
15) - stories          Download user's stories
16) - album            Download user's album
17) - igtv             Get user's IGTV
18) - hashtag_media    Get all media files from a specific hashtag
19) - hashtag_search   Search for hashtags with a search query
20) - Exit  
-------------------=>:6
[+]Enter target --=>:jordan.bown
urllib3.exceptions.ResponseError: too many 429 error responses

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests/adapters.py", line 486, in send
  File "urllib3/connectionpool.py", line 941, in urlopen
  File "urllib3/connectionpool.py", line 941, in urlopen
  File "urllib3/connectionpool.py", line 941, in urlopen
  File "urllib3/connectionpool.py", line 931, in urlopen
  File "urllib3/util/retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/jordan.bown/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Osintgram.py", line 634, in <module>
    Osintgram()
  File "Osintgram.py", line 106, in __init__
    self.menu()
  File "Osintgram.py", line 185, in menu
    self.get_target()
  File "Osintgram.py", line 210, in get_target
    target_id = self.get_target_id()
                ^^^^^^^^^^^^^^^^^^^^
  File "Osintgram.py", line 223, in get_target_id
    return self.cl.user_id_from_username(self.username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "instagrapi/mixins/user.py", line 50, in user_id_from_username
  File "instagrapi/mixins/user.py", line 200, in user_info_by_username
  File "instagrapi/mixins/user.py", line 163, in user_info_by_username_v1
  File "instagrapi/mixins/private.py", line 542, in private_request
  File "instagrapi/mixins/private.py", line 527, in private_request
  File "instagrapi/mixins/private.py", line 346, in _send_private_request
  File "requests/sessions.py", line 602, in get
  File "requests/sessions.py", line 589, in request
  File "requests/sessions.py", line 703, in send
  File "requests/adapters.py", line 510, in send
requests.exceptions.RetryError: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/jordan.bown/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
[9976] Failed to execute script 'Osintgram' due to unhandled exception!

how to fix that?

**Comment by EchterAlsFake** [comment]
Hey, it's probably not the solution that you expected, but you just need to change your IP address.

Instagram just blocks users from time to time, when they make too many requests. I also had that Issue, but changing IP solved it. 

Errors are also mostly an Issue from Instagram or the instagrapi API. 


But still thanks for reporting.

You can use VPN's like ProtonVPN, which have a Free Tier :)
