### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by b4j0n1tz** [EchterAlsFake/Osintgram2#5]
Hello im trying to use this tool and when I try to Get email of users followed by target or  Get phone number of users followed by target this is happening.

this is the error

: ------------------=>:9                                                                                                                                                                     
Traceback (most recent call last):                                                                                                                                                          
  File "/home/kali/Desktop/Osintgram2-1.1.1/Osintgram.py", line 676, in <module>                                                                                                            
    Osintgram()                                                                                                                                                                             
  File "/home/kali/Desktop/Osintgram2-1.1.1/Osintgram.py", line 106, in __init__                                                                                                            
    self.menu()                                                                                                                                                                             
  File "/home/kali/Desktop/Osintgram2-1.1.1/Osintgram.py", line 202, in menu                                                                                                                
    method()                                                                                                                                                                                
  File "/home/kali/Desktop/Osintgram2-1.1.1/Osintgram.py", line 139, in <lambda>                                                                                                            
    "9": lambda: self.get_number(mode="9"),                                                                                                                                                 
                 ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                  
  File "/home/kali/Desktop/Osintgram2-1.1.1/Osintgram.py", line 413, in get_number                                                                                                          
    usernames = [follower.username for follower in followers]                                                                                                                               
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                               
TypeError: 'NoneType' object is not iterable

**Comment by EchterAlsFake** [comment]
Hi, there are currently some issues with Osintgram2.

I had some struggles with school, but now I have holidays, so I will look at it later. I am also trying to find some ways to support accounts which have a lot of media objects and that instagram doesn't block users all the time.   Hope I can fix it soon :)

**Comment by b4j0n1tz** [comment]
thanks and no hurry bro :)
