### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by Hareshkumar77** [EchterAlsFake/Osintgram2#8]
[+]Enter target --=>:memerpaiyan2023
urllib3.exceptions.ResponseError: too many 429 error responses

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests/adapters.py", line 486, in send
  File "urllib3/connectionpool.py", line 945, in urlopen
  File "urllib3/connectionpool.py", line 945, in urlopen
  File "urllib3/connectionpool.py", line 945, in urlopen
  File "urllib3/connectionpool.py", line 935, in urlopen
  File "urllib3/util/retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/memerpaiyan2023/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Osintgram.py", line 870, in <module>
    execute()
  File "Osintgram.py", line 833, in execute
    Osintgram()
  File "Osintgram.py", line 141, in __init__
    self.menu()
  File "Osintgram.py", line 240, in menu
    self.get_target()
  File "Osintgram.py", line 320, in get_target
    target_id = self.get_target_id()
                ^^^^^^^^^^^^^^^^^^^^
  File "Osintgram.py", line 340, in get_target_id
    return self.cl.user_id_from_username(self.target)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "instagrapi/mixins/user.py", line 50, in user_id_from_username
  File "instagrapi/mixins/user.py", line 200, in user_info_by_username
  File "instagrapi/mixins/user.py", line 163, in user_info_by_username_v1
  File "instagrapi/mixins/private.py", line 542, in private_request
  File "instagrapi/mixins/private.py", line 527, in private_request
  File "instagrapi/mixins/private.py", line 346, in _send_private_request
  File "requests/sessions.py", line 602, in get
  File "requests/sessions.py", line 589, in request
  File "requests/sessions.py", line 703, in send
  File "requests/adapters.py", line 510, in send
requests.exceptions.RetryError: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/memerpaiyan2023/usernameinfo/ (Caused by ResponseError('too many 429 error responses'))
[1238] Failed to execute script 'Osintgram' due to unhandled exception!

**Comment by EchterAlsFake** [comment]
Hi,

This is an error from the Instagrapi API / instagram. I can't do anything about it, but I'll try to restructure this project to make the process of loading media files a bit smarter, so that it's more efficient, but I won't make that this year, sorry.
